import type { Metadata } from "next";
import "./globals.css";
import {ThemeProvider} from "@/components/shared/theme-provider";
import { Toaster } from "sonner";
import ReactQueryProvider from "@/lib/provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <ReactQueryProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Toaster position={"top-center"}/>
            {children}
        </ThemeProvider>
    </ReactQueryProvider>

    </body>
    </html>
  );
}
